### PR TITLE
Upgrade pytest-selenium to Version 4.0.0

### PR DESCRIPTION
**Pull request by rxm7706**
Bring in line with Grayskull
Align dependencies from source
https://github.com/pytest-dev/pytest-selenium/blob/master/pyproject.toml

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested pytest-variables >=2.0.0
-   - nothing provides requested pytest-base-url >=2.0.0

Will need to update
https://github.com/conda-forge/pytest-base-url-feedstock
https://github.com/conda-forge/pytest-variables-feedstock

**Comment by rxm7706** [comment]
Hi @birdsarah @davehunt 

Dependency PRs to update pytest-selenium to version 4.0,0 are ready to review. 
Once they are merged, I can mark this PR as ready to review. 
Thank you. 

https://github.com/conda-forge/pytest-variables-feedstock/pull/9
https://github.com/conda-forge/pytest-base-url-feedstock/pull/5

**Comment by rxm7706** [comment]
@conda-forge-admin, please restart ci

**Comment by rxm7706** [comment]
@nicoddemus ready for review

**Comment by nicoddemus** [comment]
Thanks!

**Pull request merged**
